name: dart_application_2024
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  meta: ^1.14.0
  path: ^1.8.0
  riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  lints: ^3.0.0
  test: ^1.24.0
